t=int(input())
for i in range(t):
    n=int(input())
    count=0
    while(n>0):
        if(n%100==0):
            count+=1
            n=n-100
        elif(n%50==0):
            count+=1
            n=n-50
        elif(n%10==0):
            count+=1
            n=n-10
        elif(n%5==0):
            count+=1
            n=n-5
        elif(n%2==0):
            count+=1
            n=n-2
        elif(n%1==0):
            count+=1
            n=n-1
    print(count)
