t=int(input())
for i in range(t):
    n=int(input())
    count=0
    while(n>0):
        if(n>=100):
            count+=(n//100)
            n=n-((n//100)*100)
        elif(n>=50):
            count+=(n//50)
            n=n-((n//50)*50)
        elif(n>=10):
            count+=(n//10)
            n=n-((n//10)*10)
        elif(n>=5):
            count+=(n//5)
            n=n-((n//5)*5)
        elif(n>=2):
            count+=(n//2)
            n=n-((n//2)*2)
        elif(n>=1):
            count+=(n//1)
            n=n-((n//1)*1)
    print(count)
